# Twitter Credentials

consumer_key: 'TELCCOVPhaHiZ8edxiOAIhpnJ'
consumer_secret: 'Kg7SNyzRqcd8sb6b1ib9zTNQJrycvudigfuHpyTMGBxOQU6ZEz'
oauth_token: '1646168886977392640-X0WRNCeJtIHhukHe7q9lbWvWAkH5Ke'
oauth_token_secret: '2rS44dAgR8GJensrvgr2g2r7jneXgZp1QZFlTYWCk2Ox2'